#!/bin/bash

echo "🛒 Cart Price Calculation Test"
echo "=============================="
echo ""

# Test the application is running
if curl -s http://localhost:3001 > /dev/null; then
    echo "✅ Application is running"
else
    echo "❌ Application is not running!"
    echo "Please run: npm run dev"
    exit 1
fi

echo ""
echo "🧪 Cart Price Testing Checklist:"
echo "================================"
echo ""
echo "1. 💰 Price Display Test:"
echo "   • Navigate to /cart"
echo "   • Add products to cart"
echo "   • Check individual item prices show 2 decimal places"
echo "   • Verify subtotal calculation is correct"
echo "   • Check delivery charge logic (₹50 under ₹500, FREE over ₹500)"
echo "   • Verify final total calculation"
echo ""
echo "2. 🔢 Number Formatting Test:"
echo "   • All prices should show 2 decimal places (₹10.00, not ₹10)"
echo "   • Calculations should handle decimal numbers correctly"
echo "   • No NaN or undefined values should appear"
echo ""
echo "3. 📱 Real-time Updates Test:"
echo "   • Change item quantities"
echo "   • Verify prices update instantly"
echo "   • Check that totals recalculate correctly"
echo ""
echo "4. 🛡️ Edge Cases Test:"
echo "   • Test with cart having ₹499 total (should have ₹50 delivery)"
echo "   • Test with cart having ₹501 total (should have FREE delivery)"
echo "   • Test removing all items (should show ₹0.00)"
echo ""
echo "🌐 Open: http://localhost:3001/cart"
echo ""

# Test price calculation examples
echo "📊 Expected Price Calculation Examples:"
echo "======================================"
echo ""
echo "Example 1 - Under ₹500:"
echo "  Item 1: ₹250.00 × 1 = ₹250.00"
echo "  Item 2: ₹200.00 × 1 = ₹200.00"
echo "  Subtotal: ₹450.00"
echo "  Delivery: ₹50.00"
echo "  Total: ₹500.00"
echo ""
echo "Example 2 - Over ₹500:"
echo "  Item 1: ₹300.00 × 2 = ₹600.00"
echo "  Subtotal: ₹600.00"
echo "  Delivery: FREE"
echo "  Total: ₹600.00"
echo ""
echo "✨ All prices should be formatted to 2 decimal places!"
echo "📋 If you see any issues, check browser console for errors."
