import { Inter,Poppins,Italiana,Caveat,Satisfy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter'
});


const poppins= Poppins({
  subsets: ["latin"],
  weight: ['400', '700','600'],
  variable: '--font-poppins'
});

const italiana=Italiana({
  weight: '400',
  subsets: ['latin'], 
  variable: '--font-italiana',
})

const caveat = Caveat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-caveat', 
});

const satisfy = Satisfy({
  weight:'400',
  subsets:['latin'],
  variable:'--font-satisfy'
})

export const metadata = {
  title: "EFTA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${inter.variable} ${poppins.variable} ${italiana.variable} ${caveat.variable} ${satisfy.variable}`}>
        <Navbar/>
        {children}
        <Footer />
        </body>
    </html>
  );
}
