import { Inter,Poppins,Italiana,Caveat,Satisfy,Instrument_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ModalProvider from "@/components/ModalProvider";
import { Toaster } from "react-hot-toast";
import ConditionalNavbar from "@/components/ConditionalNavbar";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const instrumentSerif = Instrument_Serif({
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-instrument-serif", 
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "600"],
  variable: "--font-poppins",
});

const italiana = Italiana({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-italiana",
});

const caveat = Caveat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-caveat', 
});

const satisfy = Satisfy({
  weight:'400',
  subsets:['latin'],
  variable:'--font-satisfy'
})

export const metadata = {
  title: "EFTA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="./logo.svg" />
      </head>
      <body className={`${inter.variable} ${poppins.variable} ${italiana.variable} ${caveat.variable} ${satisfy.variable} ${instrumentSerif.variable} overflow-x-hidden`}>
        <div className="w-full overflow-x-hidden">
        <ConditionalNavbar/>
        {children}
        <ModalProvider />
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: '#363636',
              color: '#fff',
            },
            success: {
              duration: 3000,
              theme: {
                primary: '#4aed88',
              },
            },
          }}
        />
        </div>
      </body>
    </html>
  );
}
