import { Inter,Poppins,Italiana } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter'
});

const poppins= Poppins({
  subsets: ["latin"],
  weight: ['400', '700','600'],
  variable: '--font-poppins'
});

const italiana=Italiana({
  weight: '400',
  subsets: ['latin'], 
  variable: '--font-italiana',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${inter.variable} ${poppins.variable} ${italiana.variable}`}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
