/**
 * Database Migration Script: Auto-generate category tags from titles
 * 
 * This script updates all existing event categories to have auto-generated tags
 * based on their titles (lowercase, no spaces, URL-friendly format).
 * 
 * Run this script once after updating the admin interface.
 */

const mongoose = require('mongoose');
require('dotenv').config();

// MongoDB connection
const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  throw new Error('Please define the MONGODB_URI environment variable inside .env');
}

async function connectDB() {
  try {
    if (mongoose.connection.readyState >= 1) {
      return;
    }
    
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');
  } catch (error) {
    console.error('❌ MongoDB connection error:', error);
    throw error;
  }
}

// Event Category Schema
const eventCategorySchema = new mongoose.Schema({
  title: {
    type: String,
    required: [true, 'Event category title is required'],
    trim: true
  },
  tag: {
    type: String,
    required: [true, 'Event category tag is required'],
    trim: true,
    lowercase: true,
    unique: true
  },
  color: {
    type: String,
    required: [true, 'Color is required'],
    enum: ['#FB7D76', '#F06995', '#DB53AA', '#9B59B6', '#E74C3C', '#3498DB', '#2ECC71', '#F39C12', '#E67E22', '#95A5A6'],
    default: '#FB7D76'
  },
  emoji: {
    type: String,
    default: '',
    trim: true
  },
  icon: {
    type: String,
    default: '',
    trim: true
  },
  products: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product'
  }],
  isActive: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true
});

const EventCategory = mongoose.models.EventCategory || mongoose.model('EventCategory', eventCategorySchema);

// Function to generate URL-friendly tag from title
function generateTagFromTitle(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '') // Remove special characters
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
    .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
}

async function migrateEventCategoryTags() {
  try {
    console.log('🚀 Starting Event Category Tag Migration...');
    
    // Connect to database
    await connectDB();
    console.log('✅ Connected to database');
    
    // Get all event categories
    const categories = await EventCategory.find({});
    console.log(`📊 Found ${categories.length} categories to process`);
    
    if (categories.length === 0) {
      console.log('ℹ️ No categories found to migrate');
      return;
    }
    
    let updateCount = 0;
    let skipCount = 0;
    const duplicateChecks = new Map();
    
    for (const category of categories) {
      const currentTag = category.tag;
      const autoGeneratedTag = generateTagFromTitle(category.title);
      
      console.log(`\n📝 Processing: "${category.title}"`);
      console.log(`   Current tag: "${currentTag}"`);
      console.log(`   Generated tag: "${autoGeneratedTag}"`);
      
      // Check if tag needs updating
      if (currentTag === autoGeneratedTag) {
        console.log(`   ⏭️ Skipping - tag already matches generated format`);
        skipCount++;
        continue;
      }
      
      // Check for potential duplicates
      if (duplicateChecks.has(autoGeneratedTag)) {
        console.log(`   ⚠️ Warning: Duplicate tag "${autoGeneratedTag}" detected`);
        console.log(`   Previous category: "${duplicateChecks.get(autoGeneratedTag)}"`);
        console.log(`   Current category: "${category.title}"`);
        
        // Handle duplicate by appending a number
        let uniqueTag = autoGeneratedTag;
        let counter = 2;
        
        while (duplicateChecks.has(uniqueTag) || await EventCategory.findOne({ tag: uniqueTag, _id: { $ne: category._id } })) {
          uniqueTag = `${autoGeneratedTag}-${counter}`;
          counter++;
        }
        
        console.log(`   🔧 Using unique tag: "${uniqueTag}"`);
        duplicateChecks.set(uniqueTag, category.title);
        
        // Update category with unique tag
        await EventCategory.findByIdAndUpdate(category._id, { tag: uniqueTag });
        console.log(`   ✅ Updated with unique tag`);
        updateCount++;
      } else {
        // Check if generated tag already exists in database
        const existingCategory = await EventCategory.findOne({ 
          tag: autoGeneratedTag, 
          _id: { $ne: category._id } 
        });
        
        if (existingCategory) {
          console.log(`   ⚠️ Tag "${autoGeneratedTag}" already exists for category: "${existingCategory.title}"`);
          
          // Handle duplicate by appending a number
          let uniqueTag = autoGeneratedTag;
          let counter = 2;
          
          while (await EventCategory.findOne({ tag: uniqueTag, _id: { $ne: category._id } })) {
            uniqueTag = `${autoGeneratedTag}-${counter}`;
            counter++;
          }
          
          console.log(`   🔧 Using unique tag: "${uniqueTag}"`);
          duplicateChecks.set(uniqueTag, category.title);
          
          // Update category with unique tag
          await EventCategory.findByIdAndUpdate(category._id, { tag: uniqueTag });
          console.log(`   ✅ Updated with unique tag`);
          updateCount++;
        } else {
          // Tag is unique, proceed with update
          duplicateChecks.set(autoGeneratedTag, category.title);
          
          // Update category
          await EventCategory.findByIdAndUpdate(category._id, { tag: autoGeneratedTag });
          console.log(`   ✅ Updated successfully`);
          updateCount++;
        }
      }
    }
    
    console.log('\n🎉 Migration completed successfully!');
    console.log(`📊 Summary:`);
    console.log(`   - Total categories: ${categories.length}`);
    console.log(`   - Updated: ${updateCount}`);
    console.log(`   - Skipped (already correct): ${skipCount}`);
    
    // Verify migration
    console.log('\n🔍 Verifying migration...');
    const updatedCategories = await EventCategory.find({});
    const allTagsValid = updatedCategories.every(cat => {
      const expectedTag = generateTagFromTitle(cat.title);
      const isValid = cat.tag === expectedTag || cat.tag.startsWith(expectedTag + '-');
      if (!isValid) {
        console.log(`❌ Invalid tag found: "${cat.tag}" for "${cat.title}"`);
      }
      return isValid;
    });
    
    if (allTagsValid) {
      console.log('✅ All tags are now in correct format');
    } else {
      console.log('❌ Some tags still need attention');
    }
    
    // Close database connection
    await mongoose.connection.close();
    console.log('✅ Database connection closed');
    
  } catch (error) {
    console.error('💥 Migration failed:', error);
    throw error;
  }
}

// Run migration
migrateEventCategoryTags()
  .then(() => {
    console.log('✨ Migration script completed');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Migration script failed:', error);
    process.exit(1);
  });

module.exports = { migrateEventCategoryTags, generateTagFromTitle };
